---
dependencies:
  app_lang_selector: ^0.0.1
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.1.1
  shared_preferences: ^2.2.3
  tutorial_coach_mark: ^1.2.12
description: "A tool for showing tutorials."
dev_dependencies:
  auto_exporter: any
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: any
environment:
  flutter: ">=1.17.0"
  sdk: ">=3.4.0 <4.0.0"
flutter:
  assets:
    - assets/localizations/
name: colaxy_tutorial
repository: https://github.com/normidar/colaxy_tutorial
version: 0.0.2
